/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AsuLazyImport = createFileRoute('/asu')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AsuLazyRoute = AsuLazyImport.update({
  id: '/asu',
  path: '/asu',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/asu.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/asu': {
      id: '/asu'
      path: '/asu'
      fullPath: '/asu'
      preLoaderRoute: typeof AsuLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/asu': typeof AsuLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/asu': typeof AsuLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/asu': typeof AsuLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asu'
  id: '__root__' | '/' | '/asu'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AsuLazyRoute: typeof AsuLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AsuLazyRoute: AsuLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/asu"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/asu": {
      "filePath": "asu.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
