/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const MultiplayerIdLazyImport = createFileRoute('/multiplayer/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MultiplayerIdLazyRoute = MultiplayerIdLazyImport.update({
  id: '/multiplayer/$id',
  path: '/multiplayer/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/multiplayer/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/multiplayer/$id': {
      id: '/multiplayer/$id'
      path: '/multiplayer/$id'
      fullPath: '/multiplayer/$id'
      preLoaderRoute: typeof MultiplayerIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/multiplayer/$id': typeof MultiplayerIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/multiplayer/$id': typeof MultiplayerIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/multiplayer/$id': typeof MultiplayerIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/multiplayer/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/multiplayer/$id'
  id: '__root__' | '/' | '/multiplayer/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MultiplayerIdLazyRoute: typeof MultiplayerIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MultiplayerIdLazyRoute: MultiplayerIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/multiplayer/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/multiplayer/$id": {
      "filePath": "multiplayer/$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
